# yaml-language-server: $schema=../schema.json
env: []

windows:
  - title: IDE
    leftside:
      cmd: "  nvim"
      working_directory: &fe ../../spectrum-frontend/
    rightside:
      cmd: "  pnpm exec tsc --watch --noEmit --noErrorTruncation"
      norun: true
      working_directory: *fe

  - title: DEV
    # leftside:
    cmd: "  pnpm dev"
    working_directory: *fe

    # rightside:
    #   cmd: "  tools/generate-tree-helper ~/Repositories/open-search-data-loader/initial-tree-v0_2_5.json"
    #   working_directory: *fe
    #   norun: true

  - title: PY
    cmd: "  nvim"
    working_directory: &server ../../spectrum-backend/

  - title: DEV
    rightside:
      cmd: "  uv run uvicorn src.ats.main:app --reload"
      working_directory: *server
      norun: true
    leftside:
      cmd: "  uv run pyliquibase"
      working_directory: *server
      norun: true

  # - title: GIT
  #   rightside:
  #     cmd: "  git commit --no-verify"
  #     working_directory: *fe
  #     norun: true
  #   leftside:
  #     cmd: "  git diff --staged --ignore-all-space | delta"
  #     working_directory: *fe
  #     norun: true

  - title: INFRA
    cmd: "  nvim"
    working_directory: ../../spectrum-infra/

  - title: DEPLOY
    working_directory: &cdk_dir ../../spectrum-infra/cdk/
    cmd: "  AWS_REGION=me-south-1 pnpm cdk deploy -e ..."
    norun: true

  - title: INVOKE
    working_directory: *cdk_dir
    cmd: "   aws lambda invoke --region me-south-1 --function-name spectrum-migration-runner-spectrummigrationrunnerd-7tvuaaSpJ0HJ /dev/stdout | jq"
    norun: true

  - title: SYNC
    working_directory: ../../spectrum-backend/pgsync/
    leftside:
      upperside:
        cmd: |
          podman run -it --replace --rm \
            -p 9200:9200 -p 9600:9600 \
            -e OPENSEARCH_INITIAL_ADMIN_PASSWORD='zqPA+HyG0DbLc++UxCt8YNc9adM=' \
            -e "discovery.type=single-node" \
            -e "plugins.security.disabled=true" \
            --name opensearch-node opensearchproject/opensearch:latest
        # norun: true

      lowerside:
        cmd: |
          podman run -it --replace --rm \
            -p 127.0.0.1:5601:5601 \
            -e 'OPENSEARCH_HOSTS=["http://host.containers.internal:9200"]' \
            -e 'DISABLE_SECURITY_DASHBOARDS_PLUGIN=true' \
            --name opensearch-dashboards docker.io/opensearchproject/opensearch-dashboards:latest

    rightside:
      cmd: |
        export PG_URL=postgresql://postgres:@localhost/spectrumlocal
        export PG_DRIVER=psycopg2
        export ELASTICSEARCH_HOST=localhost
        export ELASTICSEARCH_USER=admin
        export ELASTICSEARCH_PASSWORD="P@ssw0rd__TTHrovnXAM9Zeu8XnWcoT+fqs4A="
        export PG_DRIVER=psycopg2
        export OPENSEARCH=true

          CONSOLE_LOGGING_HANDLER_MIN_LEVEL=DEBUG PYTHONPATH=$PWD uvx pgsync --config schema.json --wal --verbose
      norun: true

  - title: GEN
    working_directory: ../../s/
    leftside:
      cmd: "  time bun generate-mock.ts 100"
      norun: true
    rightside:
      cmd: "  \\clear && curl localhost:9200/spectrumlocal/_doc/C0014007 | jq"
      norun: true

  # - title: TREE
  #   leftside:
  #     cmd: "  nvim data-loader.py"
  #     working_directory: &dl ../../open-search-data-loader/
  #   rightside:
  #     cmd: "  python data-loader.py data/ | jq -C | less -R"
  #     working_directory: *dl
  #     norun: true

  # - title: T
  #   leftside:
  #     cmd: "  nvim data/"
  #     working_directory: *dl
  #     norun: true
  #   rightside:
  #     upperside:
  #       cmd: |
  #         < data/full-database-v0_3.json jq \
  #         '.hits.hits.[]._source.chapter_code' | sort -V | uniq -c
  #       norun: true
  #       working_directory: *dl
  #     lowerside:
  #       cmd: python data-loader.py data/ > initial-tree-v0_2_5.json
  #       norun: true
