# yaml-language-server: $schema=../schema.json
env: []

windows:
  - title: IDE
    working_directory: &pegasus ../../pegasus/
    cmd: "  nvim"

  - title: DEV
    leftside:
      upperside:
        cmd: pnpm run start

        norun: true
        working_directory: ../../pegasus/packages/user-service/

      lowerside:
        cmd: pnpm run start

        norun: true
        working_directory: ../../pegasus/packages/admin-service/

    rightside:
      cmd: |
        pnpm run
      working_directory: ../../pegasus/packages/backend-common/

  - title: TEST
    cmd: "  nvim"
    working_directory: &api ../../pegasus-api-testing/

  - title: INFRA
    working_directory: &infra ../../pegasus-infra/
    leftside:
      cmd: nvim
    rightside:
      cmd: |
        AWS_REGION=eu-west-1 pnpm cdk:dev deploy --all --concurrency=10 --require-approval=never
      norun: true

  - title: DEV
    leftside:
      cmd: |
        export PGPASSWORD=UMdnE9UZyaEwJ8e6kVDD
        PGPASSWORD=UMdnE9UZyaEwJ8e6kVDD psql -p 54320 -h localhost -U postgres

      norun: true
      working_directory: *pegasus
    rightside:
      working_directory: &admin-service ../../pegasus/packages/admin-portal/
      cmd: |
        pnpm exec vite

  - title: MDEV
    working_directory: ../../pegasus/packages/mobile/
    leftside:
      cmd: |
        pnpm expo start --tunnel

      norun: true
    rightside:
      cmd: |
        node ./start_cloudflared.mjs

  - title: MOCK/T
    leftside:
      working_directory: ../../pegasus/tests/
      cmd: |
        nvim
    rightside:
      working_directory: &mock-service ../../pegasus/packages/external-service-mock/
      upperside:
        cmd: pnpm run start

      lowerside:
        cmd: curl localhost:8080/api/third-party/season-cal/2025-09-24/2025-09-24 -v | jq | head -n 80
